******************************************************************** 
*  ITE Tech. Inc.                              
*  PROJECT: Intel ADL_P EC                     
*  UEFI Shell IT557xE eFlash Update            
*  FILENAME: P4-L_EC_V1.09.bin  
*  BUILD DAY: 2025/02/19-20:54:41  
******************************************************************** 
mm 66 DD -w 1 -io 
mm 66 DD -w 1 -io 
ifu239 P4-L_EC_V1.09.bin 0 /mi 
reset  
