******************************************************************** 
*  ITE Tech. Inc.                              
*  PROJECT: Intel ADL_P EC                     
*  UEFI Shell IT557xE eFlash Update            
*  FILENAME: P4_EC_V1.11.bin  
*  BUILD DAY: 2025/02/19-17:50:01  
******************************************************************** 
mm 66 DD -w 1 -io 
mm 66 DD -w 1 -io 
ifu239 P4_EC_V1.11.bin 0 /mi 
reset  
